# Generated by Django 5.1 on 2024-09-02 23:56

import custom_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_user_profile_picture_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', custom_user.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
